### PR TITLE
Add newbies

### PR DESCRIPTION
**Pull request by MFarejowicz**
Cleaned up some stuff and added some things

### CODE REVIEW

**Comment by cory2067** [comment]
besides images that dont exist yet, looks good to me

**Comment by cmnord** [comment]
petition to switch to jekyll lmao this looks so tedious

(if you guys are interested I can jekyllify it some time in like october)

**Comment by cory2067** [comment]
true this needs a jekyll magic

**Comment by MFarejowicz** [comment]
Yeah that's fair... I would also support a switch to Jekyll. This works for now though

**Pull request merged**
